apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app-container
        image: my-web-app
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: data-volume
          mountPath: /usr/src/app/node_modules
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: my-web-app-pvc
